Repository Ikcelaks/qmk_sequence_transform, pull requests merged in 2024-03, with the labels that each got.

#27 Tester
  .gitignore
  generator/sequence_transform_data.py
  keybuffer.c
  qmk_wrapper.h
  sequence_transform.c
  sequence_transform.h
  tester/Makefile
  tester/qmk_wrapper.c
  tester/sim_output_buffer.c
  tester/sim_output_buffer.h
  tester/test_all_rules.c
  tester/test_ascii_string.c
  tester/test_backspace.c
  tester/test_find_rule.c
  tester/test_perform.c
  tester/tester.c
  tester/tester.h
  tester/tester.sln
  tester/tester.vcxproj
  tester/tester_utils.c
  tester/tester_utils.h
  trie.c
  utils.c
Labels: testing

#35 Fallback cleanup
  cursor.c
  cursor.h
  keybuffer.h
  sequence_transform.c
  sequence_transform.h
  tester/test_backspace.c
  tester/test_find_rule.c
  tester/test_perform.c
  tester/test_virtual_output.c
  trie.c
  trie.h
Labels: cleanup

#31 Simulated output buffer with time travel
  cursor.c
  cursor.h
  keybuffer.h
  qmk_wrapper.h
  sequence_transform.c
  sequence_transform.h
  tester/Makefile
  tester/test_all_rules.c
  tester/test_backspace.c
  tester/test_find_rule.c
  tester/test_perform.c
  tester/test_virtual_output.c
  tester/tester.h
  tester/tester.vcxproj
  trie.c
  trie.h
Labels: enhancement

#42 Issue #38 fix
  generator/sequence_transform_data.py
Labels: enhancement

#48 Sequence tokens regex enhancement
  generator/sequence_transform_data.py
Labels: enhancement

#44 [BUGFIX]Cursor handle empty completion
  cursor.c
  cursor.h
  keybuffer.c
  sequence_transform.c
  sequence_transform.h
  tester/Makefile
  tester/test_all_rules.c
  tester/test_cursor.c
  tester/tester.h
  tester/tester.vcxproj
  trie.c
  trie.h
Labels: bug

#47 Rule search fixes
  key_stack.c
  sequence_transform.c
  trie.c
  trie.h
  utils.c
  utils.h
Labels: enhancement

#69 [CLEANUP] Standardize names #1
  cursor.c
  generator/sequence_transform_config_sample.json
  generator/sequence_transform_data.py
  generator/sequence_transform_data_sample.h
  keybuffer.c
  keybuffer.h
  rule_usage/collect_data.py
  sequence_transform.c
  sequence_transform.h
  tester/test_ascii_string.c
  tester/test_cursor.c
  tester/test_find_rule.c
  tester/test_perform.c
  tester/tester_utils.c
  trie.c
  utils.c
Labels: cleanup

#71 Const cleanup
  cursor.c
  cursor.h
  keybuffer.h
  sequence_transform.c
  sequence_transform.h
  tester/sim_output_buffer.c
  tester/sim_output_buffer.h
  tester/test_cursor.c
  tester/test_find_rule.c
  tester/test_perform.c
  tester/test_virtual_output.c
  trie.c
  trie.h
Labels: cleanup

#73 Generator config map usage + cleanup
  generator/sequence_transform_config_sample.json
  generator/sequence_transform_data.py
Labels: cleanup

#77 Extended ascii trie/refactor/bugfixes
  cursor.c
  cursor.h
  generator/sequence_transform_data.py
  key_stack.c
  key_stack.h
  keybuffer.c
  keybuffer.h
  qmk_wrapper.h
  rules.mk
  sequence_transform.c
  sequence_transform.h
  st_assert.h
  st_debug.c
  st_debug.h
  st_defaults.h
  tester/qmk_wrapper.c
  tester/sim_output_buffer.c
  tester/sim_output_buffer.h
  tester/test_all_rules.c
  tester/test_ascii_string.c
  tester/test_backspace.c
  tester/test_cursor.c
  tester/test_find_rule.c
  tester/test_perform.c
  tester/test_virtual_output.c
  tester/tester.c
  tester/tester.h
  tester/tester.vcxproj
  tester/tester_utils.c
  tester/tester_utils.h
  trie.c
  trie.h
  triecodes.c
  triecodes.h
  utils.c
  utils.h
Labels: bug, enhancement, cleanup

#75 [REFACTOR] Extended ascii trie
  cursor.c
  cursor.h
  generator/sequence_transform_data.py
  key_stack.c
  key_stack.h
  keybuffer.c
  keybuffer.h
  qmk_wrapper.h
  rules.mk
  sequence_transform.c
  sequence_transform.h
  st_assert.h
  st_debug.c
  st_debug.h
  st_defaults.h
  tester/qmk_wrapper.c
  tester/sim_output_buffer.c
  tester/sim_output_buffer.h
  tester/test_all_rules.c
  tester/test_ascii_string.c
  tester/test_backspace.c
  tester/test_cursor.c
  tester/test_find_rule.c
  tester/test_perform.c
  tester/test_virtual_output.c
  tester/tester.c
  tester/tester.h
  tester/tester.vcxproj
  tester/tester_utils.c
  tester/tester_utils.h
  trie.c
  trie.h
  triecodes.c
  triecodes.h
  utils.c
  utils.h
Labels: refactor

#80 regex fix
  generator/sequence_transform_data.py
Labels: bug

#79 Rule search false positive fix
  sequence_transform.c
  tester/test_ascii_string.c
  tester/test_find_rule.c
  tester/tester.c
  trie.c
  trie.h
Labels: bug

#84 [CLEANUP] Trailing backspace cleanup
  generator/sequence_transform_data.py
  st_debug.h
  tester/Makefile
  tester/test_ascii_string.c
  tester/test_find_rule.c
  tester/test_perform.c
  trie.c
Labels: cleanup

#86 [BUGFIX] add default rules for unmatched seq_tokens
  generator/sequence_transform_data.py
Labels: bug
